### ISSUE TITLE
能否实现类似mybatisplus的lamba方式编程

### ISSUE THREAD

**Issue by zundaren** [acmestack/gobatis#27]
数据库如果修改某个字段，那么代码中的字符串类型的字段没有提示去修改很容易产生问题，mybatisplus只需要改动entity和mapper.xml就可以了，代码与数据库对不上的地方idea会有提示

**Comment by afumu** [comment]
GO 目前没有办法做到这种提示

**Comment by afumu** [comment]
@zundaren 

你可以尝试使用这个
[https://github.com/acmestack/gorm-plus](https://github.com/acmestack/gorm-plus)
